# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ENV["LC_ALL"] = "en_US.UTF-8"

  config.vm.box = "ubuntu/xenial64"
  config.vm.define "labredesvm"
  config.vm.hostname = "labredesvm"

  # VB Guest Additions configuration:
  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_reboot = true
  else
    puts '.'
    puts 'WARN: Could not find vagrant-vbguest plugin.'
    puts 'INFO: This plugin is highly recommended as it ensures that your VB guest additions are up-to-date.'
    puts 'INFO: $ vagrant plugin install vagrant-vbguest'
    puts '.'
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # config.vm.provision "shell", path: "mininet_install.sh"
  config.vm.provision "shell", path: "core5.3.1_install.sh"

end
